### ISSUE TITLE
Vídeo explicando Back-end

### ISSUE THREAD

**Issue by CorreiaJV** [fga-eps-mds/2021.2-Noctua#102]
# Descrição 
Explicar lógica inicial do back-end e o que já foi feito visando facilitar a colaboração dos outros grupos e padronizar para futuros testes/releases

# Tarefas

- [x] Explicar sistema de envio de e-mail
- [x] Explicar como os dados do csv estão sendo salvos no banco
- [x] Criar documentação no postman

# Critérios de aceitação

- [x] Link do vídeo nos comentários da issue
- [x] Disponibilizar coleção do postman 
- [x] Ok dos times A e C nos comentários

**Comment by CorreiaJV** [comment]
[Link do vídeo](https://www.youtube.com/watch?v=rmGPQAa5uwA)
[Link Download coleção do postman](https://drive.google.com/file/d/1eqB9eFMZaBbk0xf9O1xhDUNC_bTS2gEf/view?usp=sharing) - Para utilizar é só baixar o arquivo e importar pelo próprio aplicativo do postman
[Link artigo sobre o que é streaming de dados](https://insightlab.ufc.br/entenda-como-funciona-streaming-de-dados-em-tempo-real-2/)

**Comment by EuricoAbreu** [comment]
Ok

**Comment by fellipepcs** [comment]
Ok
