### ISSUE TITLE
Aprender como criar testes unitários utilizando Jest

### ISSUE THREAD

**Issue by CorreiaJV** [fga-eps-mds/2021.2-Noctua#110]
# Descrição 
Estudar a ferramenta jest e como criar testes unitarios com ela.
# Tarefas
- [x] Aprender sobre o jest.
- [x] Criar testes unitarios.

# Critérios de aceitação
- [x] Compartilhar aprendizado com o grupo em alguma reunião ou por um vídeo

**Comment by phnog** [comment]
Aprendizado compartilhado por reunião.
