### ISSUE TITLE
Apresentação release 2 - Time A

### ISSUE THREAD

**Issue by fellipepcs** [fga-eps-mds/2021.2-Noctua#155]
## Descrição:
Gravar vídeo para apresentação da release 2 estabelecido pela https://github.com/fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps/issues/37

## Tarefas

- [x] Apresentar papéis do time 
- [x] Comentar sobre as práticas ágeis que utilizaram e métricas do time
- [x] Apresentar qual parte do projeto nosso time ficou responsável
- [x] Visão crítica do time 

## Critérios de aceitação

- [x] Vídeo upado e postado no comentário da issue mencionada

**Comment by EuricoAbreu** [comment]
Vídeo Time A Projeto Noctua
https://drive.google.com/file/d/14TxQFXZbPd1l_tq0qv3K8eDMRIc9l1y9/view?usp=sharing
