### ISSUE TITLE
Estudo das tecnologias para o projeto

### ISSUE THREAD

**Issue by fellipepcs** [fga-eps-mds/2021.2-Noctua#22]
### Tecnologias
-React
-Node
-Express
-MongoDB

Estudo fundamental para iniciar o desenvolvimento do projeto

### Tarefas

- [x]  Pesquisar sobre as bibliotecas das tecnologias citadas

- [x] Compreender a documentação das tecnologias

- [x]  Buscar como poderá ser implementado no projeto

### Critérios de aceitação

- [x]  Compartilhar as informações encontradas (sites/vídeos/resumos)

- [x]  Reunião com membros dos times para compartilhar o andamento do estudo

**Comment by EuricoAbreu** [comment]
Página das documentações das tecnologias:
	- https://reactjs.org/ (React)
	- https://nodejs.org/en/docs/ (NodeJS)
	- https://expressjs.com/ (Express)
	- https://docs.mongodb.com/ (MongoDB)
