### ISSUE TITLE
Termo de Abertura de Projeto

### ISSUE THREAD

**Issue by Julio-eng** [fga-eps-mds/2021.2-Noctua#26]
# Descrição
Começar a escrever o Termo de Abetura de Projeto. 
# Tarefa
- [x] Preencher o TAP com as informações que temos sobre o projeto (@Julio-eng @Alladin-51 ). 

# Critério de aceitação
- [x] Revisão feita pelos proprios membros do time (@ian-dcg @murilopbs ).

**Comment by Alladin-51** [comment]
Preenchemos o TAP e aguardamos a revisão.
