### ISSUE TITLE
Criar requisições no backend

### ISSUE THREAD

**Issue by MateusCaltabiano** [fga-eps-mds/2021.2-Noctua#95]
# Descrição 
Atualizar o backend

# Tarefas

- [ ] Fazer intermédio do backend com a API Brasil.io
- [ ] Adicionar token de acesso
- [x] Criar requisições

# Critérios de aceitação

- [x] Requisições na coleção do postman
- [x] Disponibilizar coleção para o time

**Comment by CorreiaJV** [comment]
Não foi possível fazer o intermédio com a api do Brasil.io, haja vista o limite de requisições por tempo que eles colocam. Como conversei com a professora vamos utilizar o csv para captura dos dados, essas requisições foram implementadas e explicadas no vídeo da issue #102
