### ISSUE TITLE
Revisão e atualização dos documentos

### ISSUE THREAD

**Issue by phnog** [fga-eps-mds/2021.2-Noctua#97]
# Descrição 
Realizar uma revisão dos documentos, corrigir e atualizar .

# Tarefas

- [x] Revisar todos os documentos já criados.
- [x] Corrigir os documentos, caso necessário. 
- [x] Atualizar os documentos. 

# Critérios de aceitação

- [x] Documentos revisados, corrigidos e atualizados no github. 
- [ ] Validação com a professora.

**Comment by EuricoAbreu** [comment]
Fiz atualizações no documento de EAP

**Comment by MtsSrs** [comment]
Task em aberto por falta de tempo
